# Feature Extraction for VSX → TESS Variable-Star Classification

This notebook extracts interpretable machine-learning features from standardized TESS light-curve FITS files.

The feature-extraction pipeline uses:

- **Input**: metadata parquet containing `lightCurvePath`
- **Light-curve source**: standardized FITS files produced by the TESS data pipeline
- **Output**: feature parquet with one row per input object
- **Parallel processing**: configurable thread pool with `WorkerCount = 16` by default

All features are computed independently for each star. Dataset-level scaling, PCA, feature selection, and model fitting are performed after the train/validation/test split to prevent information leakage.

# Complete Feature List

The actual output parquet contains **60 columns**. The list below matches the schema of:

```text
TESS_features_2026_07_29_v1_input.parquet
```

## 1. Identification and Metadata Columns

| Column | Meaning | Method / Source |
|---|---|---|
| `family` | VSX family used as the classification target | copied from input metadata |
| `VSXType` | original or mapped VSX variability type | copied from input metadata |
| `VSXId` | VSX identifier | copied from input metadata |
| `lightCurvePath` | standardized or conditionally detrended FITS path used by feature extraction | copied from input metadata |
| `rawLightCurvePath` | original raw FITS path | copied from input metadata |
| `QualityLabel` | resolved light-curve quality label | QualityLabel summarizes the fraction of cadences rejected by the TESS quality mask: clean (<10%), acceptable (10–<25%), caution (25–<40%), poor (≥40%), or missing when no usable light curve was acquired. QualityScore is the numeric encoding of those labels: 0, 1, 2, 3, and 4 respectively. A higher score therefore indicates worse or unavailable data quality. It is an ordinal pipeline-quality indicator, not a physical measurement of the star. TESS quality mask is a set of quality flags assigned by the TESS mission to identify observations that may be unreliable because of spacecraft or instrument effects, such as momentum dumps, scattered light, cosmic rays, or other anomalies. These flagged cadences are typically excluded from scientific analysis. QualityLabel summarizes the fraction of cadences removed by this mask, providing an overall indicator of the reliability of the light curve. |
| `QualityScore` | numeric encoding of `QualityLabel` | `clean=0`, `acceptable=1`, `caution=2`, `poor=3`, `missing=4` |
| `Provenance` | source of the light curve | obtained from `provenance`, then `author`; otherwise `missing` |
| `ProvenanceScore` | numeric encoding of provenance | `SPOC=0`, `QLP=1`, `TESSCut=2`; unrecognized values become `NaN` |
| `OriginalFluxMedian` | median flux before standardization or detrending | Median flux of the original downloaded light curve before standardization or detrending. |
| `OriginalFluxStd` | flux standard deviation before standardization or detrending | Flux standard deviation of the original downloaded light curve before standardization or detrending. |
| `OriginalFluxSnr` | original signal-to-noise estimate |  * See note below |
| `LowSnr` | low-SNR indicator | boolean conversion of input metadata field `lowSNR` |
| `LowQualityLightCurve` | low-quality-light-curve indicator | diagnostic flag set to true when: medianUnstable (median flux is invalid or nearly zero). lowStd (flux standard deviation is nearly zero) lowSNR (abs(medianFlux) / stdFlux < 3)

Note:
* Boolean quality-control flag indicating whether the original downloaded light curve exhibits significant quality issues, such as low signal-to-noise ratio or an excessive fraction of cadences rejected by the TESS quality mask. A `True` value identifies a light curve that met at least one of the implemented quality-control criteria.

**OriginalFluxSnr** — Estimated signal-to-noise ratio (SNR) of the original downloaded light curve before standardization or detrending, calculated as:

$$
\text{FluxSnr} = \frac{|\mathrm{median}(\mathrm{Flux})|}{\mathrm{std}(\mathrm{Flux})}
$$

A larger value indicates that the signal is stronger relative to the background scatter. This metric is used during data-quality control to identify low-SNR light curves (`LowSnr` is set when `FluxSnr < 3.0`).

## 2. Data Coverage and Cadence Features

| Column | Meaning | Method |
|---|---|---|
| `CadenceCount` | number of retained finite time-and-flux observations | `len(Flux)` after loading and finite-value filtering |
| `TimeSpanDays` | total retained observing baseline in days | `max(Time) - min(Time)` |
| `MedianCadenceDays` | median spacing between adjacent retained observations | `median(diff(Time))` |

## 3. Flux Distribution Features

| Column | Meaning | Method |
|---|---|---|
| `FluxStd` | population standard deviation of retained flux | `std(Flux)` |
| `FluxMedian` | median retained flux | 50th percentile |
| `FluxMad` | median absolute deviation from the median | `median(abs(Flux - FluxMedian))` |
| `FluxP05` | 5th percentile | `percentile(Flux, 5)` |
| `FluxP10` | 10th percentile | `percentile(Flux, 10)` |
| `FluxP90` | 90th percentile | `percentile(Flux, 90)` |
| `FluxP95` | 95th percentile | `percentile(Flux, 95)` |
| `FluxIqr` | interquartile range | `FluxP75 - FluxP25` |
| `FluxAmplitude` | full observed flux range | `FluxMax - FluxMin` |
| `FluxPercentAmplitude95To5` | robust 5th-to-95th percentile amplitude | `FluxP95 - FluxP05` |
| `FluxPercentAmplitude90To10` | robust 10th-to-90th percentile amplitude | `FluxP90 - FluxP10` |
| `FluxSkewness` | bias-corrected asymmetry of the flux distribution | `scipy.stats.skew(Flux, bias=False)` |
| `FluxKurtosis` | bias-corrected excess kurtosis of the flux distribution | `scipy.stats.kurtosis(Flux, bias=False)` |

`FluxSkewness` becomes `NaN` when there are fewer than three retained observations or the flux scatter is effectively zero. `FluxKurtosis` becomes `NaN` when there are fewer than four retained observations or the flux scatter is effectively zero.

## 4. Tail-Asymmetry Features

| Column | Meaning | Method |
|---|---|---|
| `TailUpper` | distance from the median to the 95th percentile | `FluxP95 - FluxMedian` |
| `TailLower` | distance from the 5th percentile to the median | `FluxMedian - FluxP05` |
| `TailAsymmetry` | difference between upper- and lower-tail strengths | `TailUpper - TailLower` |
| `TailRatio` | upper-tail strength relative to lower-tail strength | `TailUpper / (TailLower + Eps)` through safe division. Eps = 1e-12 |

A positive `TailAsymmetry` indicates a stronger upper flux tail. A negative value indicates a stronger lower flux tail.

## 5. Time-Domain Variability Features

| Column | Meaning | Method |
|---|---|---|
| `EtaVonNeumann` | point-to-point variation relative to total variance | `sum(diff(Flux)^2) / ((N - 1) * var(Flux))`. See Notes |
| `MaxAbsSlope` | largest absolute finite rate of flux change | `max(abs(diff(Flux) / diff(Time)))`, excluding invalid or zero time differences |
| `MedianAbsSuccessiveDiff` | typical absolute point-to-point flux change | `median(abs(diff(Flux)))` |
| `FractionBeyond1Std` | fraction of observations more than one standard deviation from the mean | `mean(abs(Flux - FluxMean) > FluxStd)` |
| `FractionBeyond2Std` | fraction of observations more than two standard deviations from the mean | `mean(abs(Flux - FluxMean) > 2 * FluxStd)` |

Notes:
**EtaVonNeumann** — Measures the smoothness of a light curve by comparing point-to-point flux changes with the overall variance. Smaller values indicate smoother, more correlated variability, while larger values indicate noisier or more rapidly changing light curves.

Reference: Kim, D.-W. & Bailer-Jones, C. A. L. (2016), *A package for the automated classification of periodic variable stars*, A&A, 587, A18. https://www.aanda.org/articles/aa/full_html/2016/03/aa27395-15/aa27395-15.html

## 6. Lomb-Scargle Period Features

https://doi.org/10.3847/1538-4365/aab766
https://arxiv.org/abs/1703.09824

The period search is constrained by:

- minimum period: `MinPeriodDays`
- effective maximum period: `min(MaxPeriodDays, 0.9 * TimeSpanDays)`
- grid density: `SamplesPerPeak`

Lomb-Scargle uses flux uncertainty weights only when a valid, positive `FluxErr` array is available. Otherwise, it runs unweighted.

| Column | Meaning | Method |
|---|---|---|
| `LsBestPeriod` | period corresponding to the largest periodogram power | `1 / LsBestFrequency` |
| `LsMaxPower` | highest Lomb-Scargle power | `max(Power)` |
| `LsFalseAlarmProbability` | false-alarm probability of the highest sampled power | `LombScargle.false_alarm_probability(LsMaxPower)` |
| `LsPeriod2` | period corresponding to the second-highest sampled power | inverse of the second-ranked frequency |
| `LsPeriod3` | period corresponding to the third-highest sampled power | inverse of the third-ranked frequency |
| `LsPower2` | second-highest sampled periodogram power | second-ranked value of `Power` |
| `LsPower3` | third-highest sampled periodogram power | third-ranked value of `Power` |
| `LsPeakPowerGap12` | difference between the strongest and second-strongest Lomb-Scargle powers | `LsMaxPower - LsPower2`; measures dominance of the primary sampled peak |
| `LsPeakPowerGap23` | difference between the second- and third-strongest Lomb-Scargle powers | `LsPower2 - LsPower3`; measures separation among secondary sampled peaks |
| `LsPowerRatio21` | second-highest power relative to the highest power | `LsPower2 / LsMaxPower` |
| `LsPowerRatio31` | third-highest power relative to the highest power | `LsPower3 / LsMaxPower` |
| `LsPeriodRatio21` | second-ranked period relative to the best period | `LsPeriod2 / LsBestPeriod` |
| `LsPeriodRatio31` | third-ranked period relative to the best period | `LsPeriod3 / LsBestPeriod` |

`LsPeriod2` and `LsPeriod3` currently represent the second- and third-highest sampled frequency-grid powers. The implementation does not require them to be separate independent local peaks.

`LsPeakPowerGap12` and `LsPeakPowerGap23` summarize how separated the ranked sampled powers are. Larger values indicate greater dominance/separation between adjacent ranked powers; they are derived once in the feature extractor so downstream analysis does not recreate Lomb-Scargle features.

## 7. Phase-Folded Morphology Features

VanderPlas, J. T. (2018). Understanding the Lomb–Scargle Periodogram. The Astrophysical Journal Supplement Series, 236(1), 16.
https://doi.org/10.3847/1538-4365/aab766

NASA TESS tutorial: https://heasarc.gsfc.nasa.gov/docs/tess/LightCurve-object-Tutorial.html

After identifying the dominant variability period using the Lomb–Scargle periodogram, each light curve is phase-folded by mapping every observation onto a single normalized cycle, where the phase ranges from 0 to 1 (representing one complete period). This aligns repeated cycles and allows their shapes to be directly compared regardless of the original observation times. Phase folding aligns repeated variability cycles, allowing stars with different observation times and periods to be compared using a common representation. Statistical descriptors are then extracted from the folded light curve to characterize its morphology independently of the absolute observation time.

The extracted morphology features summarize complementary physical aspects of the periodic brightness variation. `PhaseCurveRange` and `PhaseCurveStd` quantify the amplitude and overall variability of the folded light curve. `PhaseCurveSmoothness` measures the continuity of the phased profile, helping distinguish smoothly varying pulsators from stars with sharper brightness transitions. `PhasePeakPhase` and `PhaseTroughPhase` identify the phase locations of maximum and minimum brightness, while `PhasePeakToTroughPhaseDelta` measures the phase separation between them, providing a compact description of the light-curve shape and symmetry. Together, these features capture the characteristic morphology of periodic variable stars and complement the Lomb–Scargle period and power features by describing **how** the brightness changes during each cycle rather than **how often** it repeats.

The light curve is folded using `LsBestPeriod`, divided into `PhaseBinCount` bins, and summarized using the median flux in each nonempty bin. At least five nonempty bins are required.

| Column | Meaning | Method |
|---|---|---|
| `PhaseCurveStd` | standard deviation of the median-binned phase curve | `std(BinnedFlux)` |
| `PhaseCurveRange` | full range of the median-binned phase curve | `max(BinnedFlux) - min(BinnedFlux)` |
| `PhaseCurveSmoothness` | scatter of cyclic differences between adjacent phase bins | standard deviation of cyclic first differences |
| `PhasePeakPhase` | median phase coordinate of the maximum-flux bin | `BinnedPhase[argmax(BinnedFlux)]` |
| `PhaseTroughPhase` | median phase coordinate of the minimum-flux bin | `BinnedPhase[argmin(BinnedFlux)]` |
| `PhasePeakToTroughPhaseDelta` | shortest cyclic phase separation between peak and trough | `min(abs(PeakPhase - TroughPhase), 1 - abs(PeakPhase - TroughPhase))` |

## 8. Extraction Status Columns

| Column | Meaning | Method / Source |
|---|---|---|
| `FeatureStatus` | final outcome of feature extraction for the row | possible values include `ok`, `missing_lightcurve_path`, `missing_lightcurve_file`, `too_few_cadences`, and `failed` |
| `FeatureError` | diagnostic explanation when extraction is not successful | missing path, missing file, retained-cadence count, or exception text |

## Documented Feature Groups

| Category | Columns |
|---|---:|
| Identification and metadata | 14 |
| Coverage and cadence | 3 |
| Flux distribution | 13 |
| Tail asymmetry | 4 |
| Time-domain variability | 5 |
| Lomb-Scargle | 11 |
| Phase-folded morphology | 6 |
| Extraction status | 2 |
| **Subtotal documented above** | **58** |

The stored execution output confirms that each completed feature-extraction case contains **60 columns**. The parquet schema is the authoritative output schema for downstream analysis.

The following fields from the earlier documentation are **not present** in the actual parquet schema and have therefore been removed:

```text
Name
ticId
bestTicId
ticDistanceArcmin
trendFlag
trendScore
adfPValue
```

## Feature Redundancy Reduction

To improve the stability and interpretability of feature-importance analysis, the extractor no longer outputs:

```text
FluxVariance
FluxMean
FluxP25
FluxP75
FluxMin
FluxMax
FluxP01
FluxP99
```

The retained features preserve the main scientific information: `FluxStd` for standard dispersion, `FluxMedian` for central location, `FluxIqr` for robust spread, `FluxAmplitude` for the full range, and `FluxP05`/`FluxP95` plus the tail features for robust amplitude and asymmetry. This redundancy reduction removes eight derived flux columns from the extractor.

## Additional Redundancy Reduction

`LsBestFrequency` was removed because it is an exact one-to-one transformation of `LsBestPeriod`:

\[
\mathrm{LsBestFrequency} = \frac{1}{\mathrm{LsBestPeriod}}
\]

`LsBestPeriod` is retained as the period representation in days. `LowQualityLightCurve` remains in the output feature table. The executed feature-extraction cases produce **60 output columns**, including `FeatureStatus` and `FeatureError`.

# Imports and Configuration

In [1]:
from __future__ import annotations

import logging
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import numpy as np
import pandas as pd

import lightkurve as lk
from astropy.io import fits
from astropy.timeseries import LombScargle
from scipy.stats import skew, kurtosis

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s:%(name)s:%(message)s",
)

Logger = logging.getLogger("FeatureExtractorNotebook")

Project_Root = Path(os.environ.get("Project_Root", "/data/projects/TESS_Research_RASTI_Publication"))

MinPeriodDays = 0.05
MaxPeriodDays = 100.0
SamplesPerPeak = 10
MinCadences = 100
PhaseBinCount = 20
WorkerCount = 16
Eps = 1e-12

QLP_TESSCUT_COMPARISON_INPUT_QC = Project_Root / "data/processed/QLP_TESSCut_Metadata_Consolidated_QC.parquet"
QLP_TESSCUT_COMPARISON_OUTPUT_QC = Project_Root / "data/processed/QLP_TESSCut_features_QC.parquet"
QLP_TESSCUT_COMPARISON_INPUT_DETREND = Project_Root / "data/raw/comparisons/QLP_TESSCut_Metadata_Consolidated_Detrended.parquet"
QLP_TESSCUT_COMPARISON_OUTPUT_DETREND = Project_Root / "data/raw/comparisons/QLP_TESSCut_features_Detrended.parquet"

SPOC_TESSCUT_COMPARISON_INPUT_QC = Project_Root / "data/processed/SPOC_TESSCut_Metadata_Consolidated_QC.parquet"
SPOC_TESSCUT_COMPARISON_OUTPUT_QC = Project_Root / "data/processed/SPOC_TESSCut_features_QC.parquet"
SPOC_TESSCUT_COMPARISON_INPUT_DETREND = Project_Root / "data/raw/comparisons/SPOC_TESSCut_Metadata_Consolidated_Detrended.parquet"
SPOC_TESSCUT_COMPARISON_OUTPUT_DETREND = Project_Root / "data/raw/comparisons/SPOC_TESSCut_features_Detrended.parquet"

QualityScoreMap = {
    "clean": 0,
    "acceptable": 1,
    "caution": 2,
    "poor": 3,
    "missing": 4,
}

ProvenanceScoreMap = {
    "SPOC": 0,
    "QLP": 1,
    "TESSCut": 2,
}

FeatureExtractionCases = {
    "NoDetrend": {
        "InputMetadataPath": Project_Root / "data/sample/TESSAugmented_QC.parquet",
        "OutputFeaturePath": Project_Root / "data/processed/TESS_features.parquet",
    },
    "TesscutConditionalDetrend": {
        "InputMetadataPath": Project_Root / "data/raw/detrended_tesscut/TESSAugmented_QC_tesscut_conditional_detrended.parquet",
        "OutputFeaturePath": Project_Root / "data/raw/detrended_tesscut/TESS_conditional_detrended_features.parquet",
    },
    "SpocTesscutComparisonQC": {
        "InputMetadataPath": Path(SPOC_TESSCUT_COMPARISON_INPUT_QC),
        "OutputFeaturePath": Path(SPOC_TESSCUT_COMPARISON_OUTPUT_QC),
    },
    "QlpTesscutComparisonQC": {
        "InputMetadataPath": Path(QLP_TESSCUT_COMPARISON_INPUT_QC),
        "OutputFeaturePath": Path(QLP_TESSCUT_COMPARISON_OUTPUT_QC),
    },
    "SpocTesscutComparisonDetrend": {
        "InputMetadataPath": Path(SPOC_TESSCUT_COMPARISON_INPUT_DETREND),
        "OutputFeaturePath": Path(SPOC_TESSCUT_COMPARISON_OUTPUT_DETREND),
    },
    "QlpTesscutComparisonDetrend": {
        "InputMetadataPath": Path(QLP_TESSCUT_COMPARISON_INPUT_DETREND),
        "OutputFeaturePath": Path(QLP_TESSCUT_COMPARISON_OUTPUT_DETREND),
    },
}

FeatureDfByCase = {}

for CaseName, Paths in FeatureExtractionCases.items():
    print(f"{CaseName}:")
    print(f"  InputMetadataPath = {Paths['InputMetadataPath']}")
    print(f"  OutputFeaturePath = {Paths['OutputFeaturePath']}")

NoDetrend:
  InputMetadataPath = /data/projects/TESS-research/data_pipeline/TESSCache/TESSAugmented_QC.parquet
  OutputFeaturePath = /data/projects/TESS-research/feature_extraction/TESS_features.parquet
TesscutConditionalDetrend:
  InputMetadataPath = /data/projects/TESS-research/detrend_tesscut/output/TESSAugmented_QC_tesscut_conditional_detrended.parquet
  OutputFeaturePath = /data/projects/TESS-research/feature_extraction/TESS_conditional_detrended_features.parquet
SpocTesscutComparisonQC:
  InputMetadataPath = /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_Metadata_Consolidated_QC.parquet
  OutputFeaturePath = /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_QC.parquet
QlpTesscutComparisonQC:
  InputMetadataPath = /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_Metadata_Consolidated_QC.parquet
  OutputFeaturePath = /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_QC.parquet
SpocTesscutComparisonDetrend:
  InputMetadataPath = /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_Metadata_Consolidated_Detrended.parquet
  OutputFeaturePath = /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_Detrended.parquet
QlpTesscutComparisonDetrend:
  InputMetadataPath = /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_Metadata_Consolidated_Detrended.parquet
  OutputFeaturePath = /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_Detrended.parquet

### Comparison dataset paths

The SPOC–TESSCut and QLP–TESSCut QC and detrending comparison paths are defined in the configuration cell from `Project_Root`. The shared extraction loop processes the six configured feature-extraction cases and writes each feature table to its configured output path.

# Utility Functions

In [2]:
def SafeFloat(Value: Any) -> float:
    try:
        FloatValue = float(Value)
    except Exception:
        return np.nan
    return FloatValue if np.isfinite(FloatValue) else np.nan


def SafeBool(Value: Any) -> bool:
    if Value is None:
        return False
    if isinstance(Value, float) and pd.isna(Value):
        return False
    return bool(Value)


def SafeDivide(Numerator: float, Denominator: float, Eps: float = Eps) -> float:
    if not np.isfinite(Numerator) or not np.isfinite(Denominator) or abs(Denominator) < Eps:
        return np.nan
    return float(Numerator / Denominator)


def ResolvePath(PathValue: Any, MetadataPath: Path) -> Optional[Path]:
    if PathValue is None:
        return None
    if isinstance(PathValue, float) and pd.isna(PathValue):
        return None

    PathObj = Path(str(PathValue))
    if PathObj.is_absolute() and PathObj.exists():
        return PathObj
    if PathObj.exists():
        return PathObj

    CandidatePath = MetadataPath.parent / PathObj
    if CandidatePath.exists():
        return CandidatePath

    return PathObj

# Light Curve Loading

In [3]:
def LoadLightCurve(LightCurvePath: Path) -> Tuple[np.ndarray, np.ndarray, Optional[np.ndarray]]:
    """Load a light curve while treating flux uncertainty as optional.

    Time and flux determine whether a cadence is scientifically usable.
    FluxErr is retained only when it is aligned with the loaded arrays and all
    retained uncertainty values are finite and strictly positive. Invalid or
    missing uncertainty therefore downgrades Lomb-Scargle from weighted to
    unweighted analysis instead of removing otherwise valid QLP cadences.
    """

    def FirstAvailableColumn(ColumnNames: list[str], CandidateNames: list[str]) -> Optional[str]:
        NameMap = {Name.upper(): Name for Name in ColumnNames}
        for CandidateName in CandidateNames:
            MatchedName = NameMap.get(CandidateName.upper())
            if MatchedName is not None:
                return MatchedName
        return None

    def ReadGenericFitsTable(FitsPath: Path) -> Tuple[np.ndarray, np.ndarray, Optional[np.ndarray]]:
        with fits.open(str(FitsPath), memmap=False) as Hdul:
            TableData = None

            for Hdu in Hdul:
                Data = getattr(Hdu, "data", None)
                if Data is not None and getattr(Data, "dtype", None) is not None and Data.dtype.names:
                    TableData = Data
                    break

            if TableData is None:
                raise ValueError("No FITS binary table with named columns was found")

            ColumnNames = list(TableData.dtype.names)

            TimeColumn = FirstAvailableColumn(
                ColumnNames,
                ["TIME", "TMID", "BJD"],
            )
            FluxColumn = FirstAvailableColumn(
                ColumnNames,
                ["FLUX", "SAP_FLUX", "PDCSAP_FLUX", "KSPSAP_FLUX", "DET_FLUX", "NORM_FLUX"],
            )
            FluxErrColumn = FirstAvailableColumn(
                ColumnNames,
                ["FLUX_ERR", "SAP_FLUX_ERR", "PDCSAP_FLUX_ERR", "KSPSAP_FLUX_ERR", "ERR_FLUX"],
            )

            if TimeColumn is None or FluxColumn is None:
                raise ValueError(
                    f"Required time/flux columns are missing. Available columns: {ColumnNames}"
                )

            Time = np.asarray(TableData[TimeColumn], dtype=float).reshape(-1)
            Flux = np.asarray(TableData[FluxColumn], dtype=float).reshape(-1)
            FluxErr = None

            if FluxErrColumn is not None:
                FluxErr = np.asarray(TableData[FluxErrColumn], dtype=float).reshape(-1)

            return Time, Flux, FluxErr

    def ExtractFromLightkurve(LightCurve) -> Tuple[np.ndarray, np.ndarray, Optional[np.ndarray]]:
        Time = np.asarray(
            getattr(LightCurve.time, "value", LightCurve.time),
            dtype=float,
        ).reshape(-1)

        Flux = np.asarray(
            getattr(LightCurve.flux, "value", LightCurve.flux),
            dtype=float,
        ).reshape(-1)

        FluxErr = None
        if hasattr(LightCurve, "flux_err") and LightCurve.flux_err is not None:
            FluxErr = np.asarray(
                getattr(LightCurve.flux_err, "value", LightCurve.flux_err),
                dtype=float,
            ).reshape(-1)

        return Time, Flux, FluxErr

    LightCurvePath = Path(LightCurvePath)

    if not LightCurvePath.exists():
        raise FileNotFoundError(str(LightCurvePath))

    Time = None
    Flux = None
    FluxErr = None
    ReadErrors = []

    # Attempt 1: standard lightkurve reader.
    try:
        LightCurve = lk.read(str(LightCurvePath))
        Time, Flux, FluxErr = ExtractFromLightkurve(LightCurve)
    except Exception as Exc:
        ReadErrors.append(f"generic lk.read: {Exc!r}")

    # Attempt 2: QLP-specific reader.
    if Time is None or Flux is None:
        try:
            LightCurve = lk.read(
                str(LightCurvePath),
                author="QLP",
                flux_column="kspsap_flux",
            )
            Time, Flux, FluxErr = ExtractFromLightkurve(LightCurve)
        except Exception as Exc:
            ReadErrors.append(f"QLP lk.read: {Exc!r}")

    # Attempt 3: direct FITS table parsing.
    if Time is None or Flux is None:
        try:
            Time, Flux, FluxErr = ReadGenericFitsTable(LightCurvePath)
        except Exception as Exc:
            ReadErrors.append(f"generic FITS parsing: {Exc!r}")
            raise ValueError(
                "Unable to read light curve. " + " | ".join(ReadErrors)
            ) from Exc

    if Time.shape != Flux.shape:
        raise ValueError(
            f"Time/Flux shape mismatch: Time={Time.shape}, Flux={Flux.shape}"
        )

    # Only Time and Flux define a valid cadence.
    CadenceMask = np.isfinite(Time) & np.isfinite(Flux)

    FilteredTime = Time[CadenceMask]
    FilteredFlux = Flux[CadenceMask]
    FilteredFluxErr = None

    # FluxErr is optional. It must never remove otherwise valid Time/Flux rows.
    if FluxErr is not None:
        if FluxErr.shape == Time.shape:
            CandidateFluxErr = FluxErr[CadenceMask]
            ValidFluxErr = np.isfinite(CandidateFluxErr) & (CandidateFluxErr > 0)

            if len(CandidateFluxErr) > 0 and np.all(ValidFluxErr):
                FilteredFluxErr = CandidateFluxErr
            else:
                Logger.debug(
                    "Ignoring unusable flux_err for %s: %d/%d retained values are finite and positive",
                    LightCurvePath,
                    int(np.sum(ValidFluxErr)),
                    len(CandidateFluxErr),
                )
        else:
            Logger.debug(
                "Ignoring flux_err shape mismatch for %s: flux_err=%s, time=%s",
                LightCurvePath,
                FluxErr.shape,
                Time.shape,
            )

    # Keep samples in chronological order.
    Order = np.argsort(FilteredTime)
    FilteredTime = FilteredTime[Order]
    FilteredFlux = FilteredFlux[Order]

    if FilteredFluxErr is not None:
        FilteredFluxErr = FilteredFluxErr[Order]

    return FilteredTime, FilteredFlux, FilteredFluxErr

# Identification and Metadata Features

In [4]:
def ExtractIdentifierAndMetadataFeatures(Row: pd.Series) -> Dict[str, Any]:
    Result: Dict[str, Any] = {}

    ColumnsToPreserve = [
        "family", "VSXType", "VSXId", "Name", "ticId", "bestTicId",
        "ticDistanceArcmin", "lightCurvePath", "rawLightCurvePath",
        "trendFlag", "trendScore", "adfPValue",
    ]

    for ColumnName in ColumnsToPreserve:
        if ColumnName in Row.index:
            Result[ColumnName] = Row.get(ColumnName)

    QualityValue = Row.get("quality", Row.get("fitsQcStatus", Row.get("lightCurveQuality", np.nan)))
    ProvenanceValue = Row.get("provenance", Row.get("author", np.nan))

    QualityLabel = str(QualityValue) if not pd.isna(QualityValue) else "missing"
    ProvenanceLabel = str(ProvenanceValue) if not pd.isna(ProvenanceValue) else "missing"

    Result.update({
        "QualityLabel": QualityLabel,
        "QualityScore": QualityScoreMap.get(QualityLabel, np.nan),
        "Provenance": ProvenanceLabel,
        "ProvenanceScore": ProvenanceScoreMap.get(ProvenanceLabel, np.nan),
        "OriginalFluxMedian": SafeFloat(Row.get("fluxMedian", np.nan)),
        "OriginalFluxStd": SafeFloat(Row.get("fluxStd", np.nan)),
        "OriginalFluxSnr": SafeFloat(Row.get("fluxSnr", np.nan)),
        "LowSnr": SafeBool(Row.get("lowSNR", False)),
        "LowQualityLightCurve": SafeBool(Row.get("lowQualityLightCurve", False)),
    })
    return Result

# Data Coverage and Flux Distribution Features

In [5]:
def ExtractBasicStatisticalFeatures(Time: np.ndarray, Flux: np.ndarray) -> Dict[str, float]:
    CadenceCount = len(Flux)
    P01, P05, P10, P25, P50, P75, P90, P95, P99 = np.percentile(
        Flux, [1, 5, 10, 25, 50, 75, 90, 95, 99]
    )
    FluxStd = float(np.std(Flux))

    return {
        "CadenceCount": float(CadenceCount),
        "TimeSpanDays": float(np.max(Time) - np.min(Time)) if CadenceCount > 1 else np.nan,
        "MedianCadenceDays": float(np.median(np.diff(Time))) if CadenceCount > 2 else np.nan,
        "FluxStd": FluxStd,
        "FluxMedian": float(P50),
        "FluxMad": float(np.median(np.abs(Flux - P50))),
        "FluxP05": float(P05),
        "FluxP10": float(P10),
        "FluxP90": float(P90),
        "FluxP95": float(P95),
        "FluxIqr": float(P75 - P25),
        "FluxAmplitude": float(np.max(Flux) - np.min(Flux)),
        "FluxPercentAmplitude95To5": float(P95 - P05),
        "FluxPercentAmplitude90To10": float(P90 - P10),
        "FluxSkewness": float(skew(Flux, bias=False)) if CadenceCount >= 3 and FluxStd > Eps else np.nan,
        "FluxKurtosis": float(kurtosis(Flux, bias=False)) if CadenceCount >= 4 and FluxStd > Eps else np.nan,
    }

# Tail-Asymmetry Features

In [6]:
def ExtractTailAsymmetryFeatures(Flux: np.ndarray) -> Dict[str, float]:
    P05, P50, P95 = np.percentile(Flux, [5, 50, 95])

    TailUpper = float(P95 - P50)
    TailLower = float(P50 - P05)
    TailAsymmetry = float(TailUpper - TailLower)
    TailRatio = SafeDivide(TailUpper, TailLower + Eps)

    return {
        "TailUpper": TailUpper,
        "TailLower": TailLower,
        "TailAsymmetry": TailAsymmetry,
        "TailRatio": TailRatio,
    }

# Time-Domain Variability Features

In [7]:
def ExtractVariabilityFeatures(Time: np.ndarray, Flux: np.ndarray) -> Dict[str, float]:
    CadenceCount = len(Flux)
    if CadenceCount < 3:
        return {
            "EtaVonNeumann": np.nan,
            "MaxAbsSlope": np.nan,
            "MedianAbsSuccessiveDiff": np.nan,
            "FractionBeyond1Std": np.nan,
            "FractionBeyond2Std": np.nan,
        }

    FluxMean = float(np.mean(Flux))
    FluxStd = float(np.std(Flux))
    FluxVariance = float(np.var(Flux))
    FluxDiff = np.diff(Flux)
    TimeDiff = np.diff(Time)

    ValidTimeDiff = np.isfinite(TimeDiff) & (np.abs(TimeDiff) > Eps)
    Slopes = FluxDiff[ValidTimeDiff] / TimeDiff[ValidTimeDiff] if np.any(ValidTimeDiff) else np.array([])

    Eta = np.sum(FluxDiff ** 2) / ((CadenceCount - 1) * FluxVariance) if FluxVariance > Eps else np.nan

    return {
        "EtaVonNeumann": float(Eta) if np.isfinite(Eta) else np.nan,
        "MaxAbsSlope": float(np.max(np.abs(Slopes))) if Slopes.size else np.nan,
        "MedianAbsSuccessiveDiff": float(np.median(np.abs(FluxDiff))),
        "FractionBeyond1Std": float(np.mean(np.abs(Flux - FluxMean) > FluxStd)) if FluxStd > Eps else np.nan,
        "FractionBeyond2Std": float(np.mean(np.abs(Flux - FluxMean) > 2 * FluxStd)) if FluxStd > Eps else np.nan,
    }

# Lomb-Scargle Period Features

In [8]:
def ExtractLombScargleFeatures(Time: np.ndarray, Flux: np.ndarray, FluxErr: Optional[np.ndarray]) -> Dict[str, float]:
    Result = {
        "LsBestPeriod": np.nan,
        "LsMaxPower": np.nan,
        "LsFalseAlarmProbability": np.nan,
        "LsPeriod2": np.nan,
        "LsPeriod3": np.nan,
        "LsPower2": np.nan,
        "LsPower3": np.nan,
        "LsPeakPowerGap12": np.nan,
        "LsPeakPowerGap23": np.nan,
        "LsPowerRatio21": np.nan,
        "LsPowerRatio31": np.nan,
        "LsPeriodRatio21": np.nan,
        "LsPeriodRatio31": np.nan,
    }

    if len(Flux) < MinCadences:
        return Result

    TimeSpan = float(np.max(Time) - np.min(Time))
    if not np.isfinite(TimeSpan) or TimeSpan <= 0:
        return Result

    MaxPeriod = min(MaxPeriodDays, 0.9 * TimeSpan)
    if MaxPeriod <= MinPeriodDays:
        return Result

    CenteredFlux = Flux - np.nanmedian(Flux)

    try:
        if FluxErr is not None and len(FluxErr) == len(Flux) and np.all(np.isfinite(FluxErr)):
            LombScargleModel = LombScargle(Time, CenteredFlux, dy=FluxErr)
        else:
            LombScargleModel = LombScargle(Time, CenteredFlux)

        Frequency, Power = LombScargleModel.autopower(
            minimum_frequency=1.0 / MaxPeriod,
            maximum_frequency=1.0 / MinPeriodDays,
            samples_per_peak=SamplesPerPeak,
        )

        FiniteMask = np.isfinite(Frequency) & np.isfinite(Power) & (Frequency > 0)
        Frequency = Frequency[FiniteMask]
        Power = Power[FiniteMask]
        if len(Power) == 0:
            return Result

        Order = np.argsort(Power)[::-1]
        BestFrequency = float(Frequency[Order[0]])
        BestPeriod = float(1.0 / BestFrequency)
        BestPower = float(Power[Order[0]])

        Result.update({
            "LsBestPeriod": BestPeriod,
            "LsMaxPower": BestPower,
            "LsFalseAlarmProbability": float(LombScargleModel.false_alarm_probability(BestPower)),
        })

        if len(Order) > 1:
            Period2 = float(1.0 / Frequency[Order[1]])
            Power2 = float(Power[Order[1]])
            Result.update({
                "LsPeriod2": Period2,
                "LsPower2": Power2,
                "LsPowerRatio21": SafeDivide(Power2, BestPower),
                "LsPeriodRatio21": SafeDivide(Period2, BestPeriod),
            })
            Result["LsPeakPowerGap12"] = BestPower - Power2

        if len(Order) > 2:
            Period3 = float(1.0 / Frequency[Order[2]])
            Power3 = float(Power[Order[2]])
            Result.update({
                "LsPeriod3": Period3,
                "LsPower3": Power3,
                "LsPowerRatio31": SafeDivide(Power3, BestPower),
                "LsPeriodRatio31": SafeDivide(Period3, BestPeriod),
            })
            if np.isfinite(Result.get("LsPower2", np.nan)):
                Result["LsPeakPowerGap23"] = Result["LsPower2"] - Power3

    except Exception as Exc:
        Logger.debug("Lomb-Scargle failed: %s", Exc)

    return Result

# Phase-Folded Morphology Features

In [9]:
def ExtractPhaseFeatures(Time: np.ndarray, Flux: np.ndarray, Period: float) -> Dict[str, float]:
    Result = {
        "PhaseCurveStd": np.nan,
        "PhaseCurveRange": np.nan,
        "PhaseCurveSmoothness": np.nan,
        "PhasePeakPhase": np.nan,
        "PhaseTroughPhase": np.nan,
        "PhasePeakToTroughPhaseDelta": np.nan,
    }

    if not np.isfinite(Period) or Period <= 0 or len(Flux) < MinCadences:
        return Result

    try:
        Phase = (Time % Period) / Period
        Order = np.argsort(Phase)
        Phase = Phase[Order]
        Flux = Flux[Order]

        BinEdges = np.linspace(0.0, 1.0, PhaseBinCount + 1)
        BinIndex = np.digitize(Phase, BinEdges) - 1

        BinnedPhase = []
        BinnedFlux = []

        for BinNumber in range(PhaseBinCount):
            BinMask = BinIndex == BinNumber
            if np.any(BinMask):
                BinnedPhase.append(float(np.median(Phase[BinMask])))
                BinnedFlux.append(float(np.median(Flux[BinMask])))

        BinnedPhase = np.asarray(BinnedPhase, dtype=float)
        BinnedFlux = np.asarray(BinnedFlux, dtype=float)
        if len(BinnedFlux) < 5:
            return Result

        PeakIndex = int(np.argmax(BinnedFlux))
        TroughIndex = int(np.argmin(BinnedFlux))
        PeakPhase = float(BinnedPhase[PeakIndex])
        TroughPhase = float(BinnedPhase[TroughIndex])

        RawDelta = abs(PeakPhase - TroughPhase)
        CyclicDelta = min(RawDelta, 1.0 - RawDelta)
        CyclicDiff = np.diff(np.r_[BinnedFlux, BinnedFlux[0]])

        Result.update({
            "PhaseCurveStd": float(np.std(BinnedFlux)),
            "PhaseCurveRange": float(np.max(BinnedFlux) - np.min(BinnedFlux)),
            "PhaseCurveSmoothness": float(np.std(CyclicDiff)),
            "PhasePeakPhase": PeakPhase,
            "PhaseTroughPhase": TroughPhase,
            "PhasePeakToTroughPhaseDelta": float(CyclicDelta),
        })

    except Exception as Exc:
        Logger.debug("Phase feature extraction failed: %s", Exc)

    return Result

# Per-Star Feature Extraction

In [10]:
def ExtractFeaturesForRow(Row: pd.Series, MetadataPath: Path) -> Dict[str, Any]:
    fitsBasePath = Project_Root / "data" / "raw"
    Result: Dict[str, Any] = {
        "FeatureStatus": "unknown",
        "FeatureError": None,
    }

    Result.update(ExtractIdentifierAndMetadataFeatures(Row))
    # LightCurvePath = ResolvePath(Row.get("lightCurvePath"), MetadataPath)
    LightCurvePath = Path(fitsBasePath / Row.get("lightCurvePath"))

    if LightCurvePath is None:
        Result["FeatureStatus"] = "missing_lightcurve_path"
        Result["FeatureError"] = "No lightCurvePath"
        return Result

    if not LightCurvePath.exists():
        Result["FeatureStatus"] = "missing_lightcurve_file"
        Result["FeatureError"] = str(LightCurvePath)
        return Result

    try:
        Time, Flux, FluxErr = LoadLightCurve(LightCurvePath)

        if len(Flux) < MinCadences:
            Result["FeatureStatus"] = "too_few_cadences"
            Result["FeatureError"] = f"Only {len(Flux)} finite cadences"
            Result["CadenceCount"] = float(len(Flux))
            return Result

        Result.update(ExtractBasicStatisticalFeatures(Time, Flux))
        Result.update(ExtractTailAsymmetryFeatures(Flux))
        Result.update(ExtractVariabilityFeatures(Time, Flux))

        LombScargleFeatures = ExtractLombScargleFeatures(Time, Flux, FluxErr)
        Result.update(LombScargleFeatures)

        BestPeriod = LombScargleFeatures.get("LsBestPeriod", np.nan)
        Result.update(ExtractPhaseFeatures(Time, Flux, BestPeriod))

        Result["FeatureStatus"] = "ok"

    except Exception as Exc:
        Result["FeatureStatus"] = "failed"
        Result["FeatureError"] = repr(Exc)

    return Result

# Dataset-Level Feature Extraction with Parallel Processing

In [11]:
def FinalizeFeatureDf(FeatureDf: pd.DataFrame) -> pd.DataFrame:
    if "_InputOrder" in FeatureDf.columns:
        FeatureDf = FeatureDf.sort_values("_InputOrder").drop(columns=["_InputOrder"]).reset_index(drop=True)
    return FeatureDf


def ExtractFeaturesSerial(MetadataDf: pd.DataFrame, MetadataPath: Path) -> pd.DataFrame:
    ResultRows = []
    for Position, (_, Row) in enumerate(MetadataDf.iterrows()):
        if Position % 100 == 0:
            Logger.info("Processing %s/%s", Position, len(MetadataDf))
        FeatureRow = ExtractFeaturesForRow(Row, MetadataPath)
        FeatureRow["_InputOrder"] = Position
        ResultRows.append(FeatureRow)
    return FinalizeFeatureDf(pd.DataFrame(ResultRows))


def ExtractFeaturesParallel(MetadataDf: pd.DataFrame, MetadataPath: Path, WorkerCount: int = WorkerCount) -> pd.DataFrame:
    ResultRows = []
    TotalRows = len(MetadataDf)
    Logger.info("Starting parallel feature extraction with WorkerCount=%s", WorkerCount)

    with ThreadPoolExecutor(max_workers=WorkerCount) as Executor:
        FutureMap = {}
        for Position, (_, Row) in enumerate(MetadataDf.iterrows()):
            Future = Executor.submit(ExtractFeaturesForRow, Row, MetadataPath)
            FutureMap[Future] = Position

        CompletedCount = 0
        for Future in as_completed(FutureMap):
            Position = FutureMap[Future]
            try:
                FeatureRow = Future.result()
            except Exception as Exc:
                FeatureRow = {"FeatureStatus": "failed", "FeatureError": repr(Exc)}

            FeatureRow["_InputOrder"] = Position
            ResultRows.append(FeatureRow)
            CompletedCount += 1

            if CompletedCount % 100 == 0 or CompletedCount == TotalRows:
                Logger.info("Completed %s/%s", CompletedCount, TotalRows)

    return FinalizeFeatureDf(pd.DataFrame(ResultRows))


def ExtractFeatures(MetadataDf: pd.DataFrame, MetadataPath: Path, WorkerCount: int = WorkerCount) -> pd.DataFrame:
    if WorkerCount <= 1:
        return ExtractFeaturesSerial(MetadataDf, MetadataPath)
    return ExtractFeaturesParallel(MetadataDf, MetadataPath, WorkerCount=WorkerCount)

# Execute Feature Extraction

In [12]:
FeatureDfByCase = {}

for CaseName, Paths in FeatureExtractionCases.items():
    print("=" * 100)
    print(f"Running feature extraction case: {CaseName}")
    print(f"Input:  {Paths['InputMetadataPath']}")
    print(f"Output: {Paths['OutputFeaturePath']}")
    print("=" * 100)

    InputMetadataPath = Paths["InputMetadataPath"]
    OutputFeaturePath = Paths["OutputFeaturePath"]

    MetadataDf = pd.read_parquet(InputMetadataPath)
    if CaseName == "TesscutConditionalDetrend":
        UseDetrendedMask = (
            MetadataDf["detrended"].fillna(False).astype(bool)
            & MetadataDf["detrendLightCurvePath"].notna()
            & MetadataDf["detrendLightCurvePath"].astype(str).str.strip().ne("")
        )

        MetadataDf.loc[
            UseDetrendedMask,
            "lightCurvePath"
        ] = MetadataDf.loc[
            UseDetrendedMask,
            "detrendLightCurvePath"
        ]

    FeatureDf = ExtractFeatures(
        MetadataDf=MetadataDf,
        MetadataPath=InputMetadataPath,
        WorkerCount=WorkerCount,
    )

    OutputFeaturePath.parent.mkdir(parents=True, exist_ok=True)
    FeatureDf.to_parquet(OutputFeaturePath, index=False)

    print(f"Saved {len(FeatureDf)} rows and {len(FeatureDf.columns)} columns to {OutputFeaturePath}")
    FeatureDf["FeatureStatus"].value_counts(dropna=False)

    FeatureDfByCase[CaseName] = FeatureDf.copy()

2026-09-07 00:26:47,486 INFO:FeatureExtractorNotebook:Starting parallel feature extraction with WorkerCount=16

====================================================================================================
Running feature extraction case: NoDetrend
Input:  /data/projects/TESS-research/data_pipeline/TESSCache/TESSAugmented_QC.parquet
Output: /data/projects/TESS-research/feature_extraction/TESS_features.parquet
====================================================================================================

WARNING: UnitsWarning: 'btjd' did not parse as fits unit: At col 0, Unit 'btjd' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
2026-09-07 00:26:47,734 WARNING:astropy:UnitsWarning: 'btjd' did not parse as fits unit: At col 0, Unit 'btjd' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
WARNING: UnitsWarning: 'btjd' did not parse as fits unit: At col 0, Unit 'btjd' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
2026-09-07 00:26:47,749 WARNING:astropy:UnitsWarning: 'btjd' did not parse as fits unit: At col 0, Unit 'btjd' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
0% (0/12767) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,773 INFO:lightkurve.utils:0% (0/12767) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/18678) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,777 INFO:lightkurve.utils:0% (0/18678) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32158) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,805 INFO:lightkurve.utils:0% (0/32158) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/53566) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,817 INFO:lightkurve.utils:0% (0/53566) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,828 INFO:lightkurve.utils:0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,839 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:47,997 INFO:lightkurve.utils:0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/36973) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:48,068 INFO:lightkurve.utils:0% (0/36973) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/26793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:48,099 INFO:lightkurve.utils:0% (0/26793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/40096) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/281759) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:48,119 INFO:lightkurve.utils:0% (0/40096) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28154) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:48,134 INFO:lightkurve.utils:0% (0/281759) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:48,135 INFO:lightkurve.utils:0% (0/28154) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25041) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:50,788 INFO:lightkurve.utils:0% (0/25041) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:51,149 INFO:lightkurve.utils:0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/26486) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:51,581 INFO:lightkurve.utils:0% (0/26486) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:51,618 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10828) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:52,128 INFO:lightkurve.utils:0% (0/10828) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:52,317 INFO:lightkurve.utils:0% (0/35355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:52,747 INFO:lightkurve.utils:0% (0/23270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:52,957 INFO:lightkurve.utils:0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14258) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:53,777 INFO:lightkurve.utils:0% (0/14258) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:53,839 INFO:lightkurve.utils:0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:54,100 INFO:lightkurve.utils:0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/75851) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:54,330 INFO:lightkurve.utils:0% (0/75851) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17196) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:54,422 INFO:lightkurve.utils:0% (0/17196) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:54,608 INFO:lightkurve.utils:0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22472) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:54,751 INFO:lightkurve.utils:0% (0/22472) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:55,056 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/18975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:55,365 INFO:lightkurve.utils:0% (0/18975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/291089) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:55,748 INFO:lightkurve.utils:0% (0/291089) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14655) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:56,247 INFO:lightkurve.utils:0% (0/14655) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/13339) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:56,395 INFO:lightkurve.utils:0% (0/13339) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/41364) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:56,704 INFO:lightkurve.utils:0% (0/41364) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/27265) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:56,934 INFO:lightkurve.utils:0% (0/27265) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/53331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:57,073 INFO:lightkurve.utils:0% (0/53331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2843) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:57,349 INFO:lightkurve.utils:0% (0/2843) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17598) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:57,789 INFO:lightkurve.utils:0% (0/17598) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16167) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:57,865 INFO:lightkurve.utils:0% (0/16167) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:57,868 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14785) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:57,880 INFO:lightkurve.utils:0% (0/14785) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:58,522 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25143) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:59,050 INFO:lightkurve.utils:0% (0/25143) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:59,400 INFO:lightkurve.utils:0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:26:59,637 INFO:lightkurve.utils:0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:00,098 INFO:lightkurve.utils:0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52376) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:00,123 INFO:lightkurve.utils:0% (0/52376) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/4458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:00,292 INFO:lightkurve.utils:0% (0/4458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/20736) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:00,796 INFO:lightkurve.utils:0% (0/20736) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:01,240 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32102) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:01,791 INFO:lightkurve.utils:0% (0/32102) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/271390) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:01,967 INFO:lightkurve.utils:0% (0/271390) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/42271) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:02,109 INFO:lightkurve.utils:0% (0/42271) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32315) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:02,475 INFO:lightkurve.utils:0% (0/32315) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/13317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:02,694 INFO:lightkurve.utils:0% (0/13317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35132) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:03,076 INFO:lightkurve.utils:0% (0/35132) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/4942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:03,106 INFO:lightkurve.utils:0% (0/4942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23075) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:03,200 INFO:lightkurve.utils:0% (0/23075) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9058) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:03,617 INFO:lightkurve.utils:0% (0/9058) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/58244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:03,915 INFO:lightkurve.utils:0% (0/58244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/39085) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:04,368 INFO:lightkurve.utils:0% (0/39085) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/46263) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:04,635 INFO:lightkurve.utils:0% (0/46263) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:05,151 INFO:lightkurve.utils:0% (0/19468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11948) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:05,479 INFO:lightkurve.utils:0% (0/11948) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:05,756 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23099) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:05,974 INFO:lightkurve.utils:0% (0/23099) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:06,288 INFO:lightkurve.utils:0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/58278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:06,638 INFO:lightkurve.utils:0% (0/58278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14055) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:06,844 INFO:lightkurve.utils:0% (0/14055) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:07,073 INFO:lightkurve.utils:0% (0/24254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/51313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:07,426 INFO:lightkurve.utils:0% (0/51313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/64915) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:07,760 INFO:lightkurve.utils:0% (0/64915) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/37793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:08,240 INFO:lightkurve.utils:0% (0/37793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/21346) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:08,345 INFO:lightkurve.utils:0% (0/21346) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/20498) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:08,373 INFO:lightkurve.utils:0% (0/20498) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43291) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:08,533 INFO:lightkurve.utils:0% (0/43291) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32101) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:08,903 INFO:lightkurve.utils:0% (0/32101) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/276410) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:08,926 INFO:lightkurve.utils:0% (0/276410) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/53831) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:27:09,504 INFO:lightkurve.utils:0% (0/53831) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Saved 7294 rows and 60 columns to /data/projects/TESS-research/feature_extraction/TESS_features.parquet
====================================================================================================
Running feature extraction case: TesscutConditionalDetrend
Input:  /data/projects/TESS-research/detrend_tesscut/output/TESSAugmented_QC_tesscut_conditional_detrended.parquet
Output: /data/projects/TESS-research/feature_extraction/TESS_conditional_detrended_features.parquet
====================================================================================================

0% (0/12767) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:12,894 INFO:lightkurve.utils:0% (0/12767) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:12,910 INFO:lightkurve.utils:0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28154) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:12,916 INFO:lightkurve.utils:0% (0/28154) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/53566) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:12,936 INFO:lightkurve.utils:0% (0/53566) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,039 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,046 INFO:lightkurve.utils:0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32158) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/26793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,055 INFO:lightkurve.utils:0% (0/32158) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/40096) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,089 INFO:lightkurve.utils:0% (0/26793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/18678) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/36973) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,100 INFO:lightkurve.utils:0% (0/40096) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,167 INFO:lightkurve.utils:0% (0/18678) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,175 INFO:lightkurve.utils:0% (0/36973) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/281759) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:13,285 INFO:lightkurve.utils:0% (0/281759) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25041) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:14,716 INFO:lightkurve.utils:0% (0/25041) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:15,620 INFO:lightkurve.utils:0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:16,035 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/26486) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:16,045 INFO:lightkurve.utils:0% (0/26486) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10828) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:17,168 INFO:lightkurve.utils:0% (0/10828) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:17,309 INFO:lightkurve.utils:0% (0/23270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:17,538 INFO:lightkurve.utils:0% (0/35355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:18,154 INFO:lightkurve.utils:0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:18,729 INFO:lightkurve.utils:0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14258) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:18,891 INFO:lightkurve.utils:0% (0/14258) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:19,455 INFO:lightkurve.utils:0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17196) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:19,534 INFO:lightkurve.utils:0% (0/17196) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/75851) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:19,592 INFO:lightkurve.utils:0% (0/75851) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22472) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:19,652 INFO:lightkurve.utils:0% (0/22472) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:19,704 INFO:lightkurve.utils:0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:20,112 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/18975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:20,197 INFO:lightkurve.utils:0% (0/18975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/291089) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:20,628 INFO:lightkurve.utils:0% (0/291089) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14655) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:21,739 INFO:lightkurve.utils:0% (0/14655) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/13339) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:21,754 INFO:lightkurve.utils:0% (0/13339) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/41364) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:21,976 INFO:lightkurve.utils:0% (0/41364) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/27265) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:22,348 INFO:lightkurve.utils:0% (0/27265) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2843) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:22,677 INFO:lightkurve.utils:0% (0/2843) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/53331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:22,784 INFO:lightkurve.utils:0% (0/53331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17598) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:23,133 INFO:lightkurve.utils:0% (0/17598) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16167) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:23,215 INFO:lightkurve.utils:0% (0/16167) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14785) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:23,672 INFO:lightkurve.utils:0% (0/14785) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:23,706 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25143) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:23,721 INFO:lightkurve.utils:0% (0/25143) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:23,722 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:24,292 INFO:lightkurve.utils:0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:24,475 INFO:lightkurve.utils:0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52376) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:24,733 INFO:lightkurve.utils:0% (0/52376) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/4458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:25,271 INFO:lightkurve.utils:0% (0/4458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/20736) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:25,347 INFO:lightkurve.utils:0% (0/20736) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:25,404 INFO:lightkurve.utils:0% (0/52596) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32102) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:26,021 INFO:lightkurve.utils:0% (0/32102) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:26,094 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/271390) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:27,079 INFO:lightkurve.utils:0% (0/271390) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/42271) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:27,089 INFO:lightkurve.utils:0% (0/42271) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/13317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:27,541 INFO:lightkurve.utils:0% (0/13317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32315) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:27,707 INFO:lightkurve.utils:0% (0/32315) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/4942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:28,115 INFO:lightkurve.utils:0% (0/4942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23075) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:28,169 INFO:lightkurve.utils:0% (0/23075) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35132) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:28,257 INFO:lightkurve.utils:0% (0/35132) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9058) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:28,777 INFO:lightkurve.utils:0% (0/9058) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/58244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:28,970 INFO:lightkurve.utils:0% (0/58244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/39085) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:29,210 INFO:lightkurve.utils:0% (0/39085) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/46263) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:29,626 INFO:lightkurve.utils:0% (0/46263) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:29,700 INFO:lightkurve.utils:0% (0/19468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:30,507 INFO:lightkurve.utils:0% (0/19770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11948) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:30,573 INFO:lightkurve.utils:0% (0/11948) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23099) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:30,863 INFO:lightkurve.utils:0% (0/23099) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14055) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:30,947 INFO:lightkurve.utils:0% (0/14055) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/58278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:31,061 INFO:lightkurve.utils:0% (0/58278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:31,294 INFO:lightkurve.utils:0% (0/254238) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:32,142 INFO:lightkurve.utils:0% (0/24254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/64915) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:32,299 INFO:lightkurve.utils:0% (0/64915) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/37793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:32,785 INFO:lightkurve.utils:0% (0/37793) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/51313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:32,804 INFO:lightkurve.utils:0% (0/51313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/20498) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:33,046 INFO:lightkurve.utils:0% (0/20498) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/21346) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:33,060 INFO:lightkurve.utils:0% (0/21346) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43291) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:33,469 INFO:lightkurve.utils:0% (0/43291) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/276410) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:33,854 INFO:lightkurve.utils:0% (0/276410) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32101) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:33,937 INFO:lightkurve.utils:0% (0/32101) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/53831) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:34,570 INFO:lightkurve.utils:0% (0/53831) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19881) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:34,729 INFO:lightkurve.utils:0% (0/19881) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:34,761 INFO:lightkurve.utils:0% (0/47803) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/33867) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:35,408 INFO:lightkurve.utils:0% (0/33867) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22096) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:35,779 INFO:lightkurve.utils:0% (0/22096) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24319) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:35,963 INFO:lightkurve.utils:0% (0/24319) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25138) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:36,029 INFO:lightkurve.utils:0% (0/25138) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14367) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 00:57:36,200 INFO:lightkurve.utils:0% (0/14367) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/57998) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Saved 7294 rows and 60 columns to /data/projects/TESS-research/feature_extraction/TESS_conditional_detrended_features.parquet
====================================================================================================
Running feature extraction case: SpocTesscutComparisonQC
Input:  /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_Metadata_Consolidated_QC.parquet
Output: /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_QC.parquet
====================================================================================================

0% (0/14848) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,745 INFO:lightkurve.utils:0% (0/14848) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/12676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,753 INFO:lightkurve.utils:0% (0/12676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31559) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,775 INFO:lightkurve.utils:0% (0/31559) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31406) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,799 INFO:lightkurve.utils:0% (0/31406) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25561) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,840 INFO:lightkurve.utils:0% (0/25561) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/34777) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,866 INFO:lightkurve.utils:0% (0/34777) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/218163) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,930 INFO:lightkurve.utils:0% (0/218163) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/60189) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,937 INFO:lightkurve.utils:0% (0/60189) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/130950) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,943 INFO:lightkurve.utils:0% (0/130950) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43481) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,944 INFO:lightkurve.utils:0% (0/43481) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/97313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:44,999 INFO:lightkurve.utils:0% (0/97313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/265282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/45957) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:45,027 INFO:lightkurve.utils:0% (0/265282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/145610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/138311) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:45,062 INFO:lightkurve.utils:0% (0/45957) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/253786) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:45,073 INFO:lightkurve.utils:0% (0/145610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:45,112 INFO:lightkurve.utils:0% (0/138311) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:45,164 INFO:lightkurve.utils:0% (0/253786) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16341) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:46,494 INFO:lightkurve.utils:0% (0/16341) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16338) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:46,741 INFO:lightkurve.utils:0% (0/16338) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:47,655 INFO:lightkurve.utils:0% (0/48355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48349) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:47,680 INFO:lightkurve.utils:0% (0/48349) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/367753) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:47,911 INFO:lightkurve.utils:0% (0/367753) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/134863) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:48,168 INFO:lightkurve.utils:0% (0/134863) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32818) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:48,704 INFO:lightkurve.utils:0% (0/32818) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/120512) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:48,718 INFO:lightkurve.utils:0% (0/120512) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/33867) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:49,072 INFO:lightkurve.utils:0% (0/33867) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/108750) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:49,076 INFO:lightkurve.utils:0% (0/108750) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/149459) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:49,252 INFO:lightkurve.utils:0% (0/149459) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43540) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:49,516 INFO:lightkurve.utils:0% (0/43540) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/66976) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:49,793 INFO:lightkurve.utils:0% (0/66976) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/103365) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:50,463 INFO:lightkurve.utils:0% (0/103365) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/71259) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:50,474 INFO:lightkurve.utils:0% (0/71259) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/103560) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:50,888 INFO:lightkurve.utils:0% (0/103560) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/68871) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:51,116 INFO:lightkurve.utils:0% (0/68871) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/54202) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:51,224 INFO:lightkurve.utils:0% (0/54202) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48919) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:51,517 INFO:lightkurve.utils:0% (0/48919) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/201409) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:51,742 INFO:lightkurve.utils:0% (0/201409) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/29770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:51,837 INFO:lightkurve.utils:0% (0/29770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/7230) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:52,638 INFO:lightkurve.utils:0% (0/7230) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47520) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:52,832 INFO:lightkurve.utils:0% (0/47520) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47456) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:53,067 INFO:lightkurve.utils:0% (0/47456) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9626) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:53,317 INFO:lightkurve.utils:0% (0/9626) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:53,338 INFO:lightkurve.utils:0% (0/25355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/50394) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:53,604 INFO:lightkurve.utils:0% (0/50394) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/100953) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:53,793 INFO:lightkurve.utils:0% (0/100953) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/82817) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:54,005 INFO:lightkurve.utils:0% (0/82817) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/114136) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:54,208 INFO:lightkurve.utils:0% (0/114136) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:54,470 INFO:lightkurve.utils:0% (0/31942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/872279) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:54,490 INFO:lightkurve.utils:0% (0/872279) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/912008) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:54,526 INFO:lightkurve.utils:0% (0/912008) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/238480) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:54,849 INFO:lightkurve.utils:0% (0/238480) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/150282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:55,243 INFO:lightkurve.utils:0% (0/150282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:55,496 INFO:lightkurve.utils:0% (0/28317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/39027) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:56,389 INFO:lightkurve.utils:0% (0/39027) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30268) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:56,410 INFO:lightkurve.utils:0% (0/30268) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9809) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:56,559 INFO:lightkurve.utils:0% (0/9809) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/29862) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:56,564 INFO:lightkurve.utils:0% (0/29862) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:57,037 INFO:lightkurve.utils:0% (0/25370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/77225) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:57,350 INFO:lightkurve.utils:0% (0/77225) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16452) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:57,363 INFO:lightkurve.utils:0% (0/16452) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/148113) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:57,728 INFO:lightkurve.utils:0% (0/148113) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/250370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:58,241 INFO:lightkurve.utils:0% (0/250370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/45909) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:58,303 INFO:lightkurve.utils:0% (0/45909) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/235425) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:58,729 INFO:lightkurve.utils:0% (0/235425) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/511114) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:58,752 INFO:lightkurve.utils:0% (0/511114) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/106270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:59,253 INFO:lightkurve.utils:0% (0/106270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/237610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:59,307 INFO:lightkurve.utils:0% (0/237610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/247385) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:59,487 INFO:lightkurve.utils:0% (0/247385) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/70392) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:27:59,910 INFO:lightkurve.utils:0% (0/70392) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/124823) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:00,308 INFO:lightkurve.utils:0% (0/124823) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:00,756 INFO:lightkurve.utils:0% (0/14676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/62748) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:00,851 INFO:lightkurve.utils:0% (0/62748) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/295794) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:01,027 INFO:lightkurve.utils:0% (0/295794) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14683) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:01,769 INFO:lightkurve.utils:0% (0/14683) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/57323) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:02,419 INFO:lightkurve.utils:0% (0/57323) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/49629) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:02,601 INFO:lightkurve.utils:0% (0/49629) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/126141) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:02,687 INFO:lightkurve.utils:0% (0/126141) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/57435) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:02,852 INFO:lightkurve.utils:0% (0/57435) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:02,896 INFO:lightkurve.utils:0% (0/15331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/151975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:03,205 INFO:lightkurve.utils:0% (0/151975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32714) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:04,044 INFO:lightkurve.utils:0% (0/32714) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/7072) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:04,462 INFO:lightkurve.utils:0% (0/7072) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17073) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:04,654 INFO:lightkurve.utils:0% (0/17073) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/88039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:04,777 INFO:lightkurve.utils:0% (0/88039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48403) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:05,048 INFO:lightkurve.utils:0% (0/48403) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/285780) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:28:05,109 INFO:lightkurve.utils:0% (0/285780) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Saved 1012 rows and 60 columns to /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_QC.parquet
====================================================================================================
Running feature extraction case: QlpTesscutComparisonQC
Input:  /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_Metadata_Consolidated_QC.parquet
Output: /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_QC.parquet
====================================================================================================

2026-09-07 01:31:00,323 INFO:FeatureExtractorNotebook:Completed 100/2732
2026-09-07 01:31:21,783 INFO:FeatureExtractorNotebook:Completed 200/2732
2026-09-07 01:31:44,664 INFO:FeatureExtractorNotebook:Completed 300/2732
2026-09-07 01:32:09,331 INFO:FeatureExtractorNotebook:Completed 400/2732
2026-09-07 01:32:29,030 INFO:FeatureExtractorNotebook:Completed 500/2732
2026-09-07 01:32:54,871 INFO:FeatureExtractorNotebook:Completed 600/2732
2026-09-07 01:33:25,382 INFO:FeatureExtractorNotebook:Completed 700/2732
2026-09-07 01:33:49,486 INFO:FeatureExtractorNotebook:Completed 800/2732
2026-09-07 01:34:10,083 INFO:FeatureExtractorNotebook:Completed 900/2732
2026-09-07 01:34:27,209 INFO:FeatureExtractorNotebook:Completed 1000/2732
2026-09-07 01:34:50,134 INFO:FeatureExtractorNotebook:Completed 1100/2732
2026-09-07 01:35:08,395 INFO:FeatureExtractorNotebook:Completed 1200/2732
2026-09-07 01:35:29,710 INFO:FeatureExtractorNotebook:Completed 1300/2732
0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:37,773 INFO:lightkurve.utils:0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/33018) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:37,845 INFO:lightkurve.utils:0% (0/33018) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:38,240 INFO:lightkurve.utils:0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:38,309 INFO:lightkurve.utils:0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:38,392 INFO:lightkurve.utils:0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/42627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:38,884 INFO:lightkurve.utils:0% (0/42627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48327) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:38,899 INFO:lightkurve.utils:0% (0/48327) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28434) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:40,119 INFO:lightkurve.utils:0% (0/28434) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:40,142 INFO:lightkurve.utils:0% (0/31244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28826) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:41,101 INFO:lightkurve.utils:0% (0/28826) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/33175) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:41,692 INFO:lightkurve.utils:0% (0/33175) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28834) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:41,989 INFO:lightkurve.utils:0% (0/28834) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:41,999 INFO:lightkurve.utils:0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,202 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,300 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24791) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,323 INFO:lightkurve.utils:0% (0/24791) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14646) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,336 INFO:lightkurve.utils:0% (0/14646) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31397) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,354 INFO:lightkurve.utils:0% (0/31397) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,357 INFO:lightkurve.utils:0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19194) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,379 INFO:lightkurve.utils:0% (0/30879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,398 INFO:lightkurve.utils:0% (0/19194) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11161) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,701 INFO:lightkurve.utils:0% (0/11161) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/12142) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:42,801 INFO:lightkurve.utils:0% (0/12142) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:43,232 INFO:lightkurve.utils:0% (0/15627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19881) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:43,498 INFO:lightkurve.utils:0% (0/19881) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30606) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:43,712 INFO:lightkurve.utils:0% (0/30606) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/41049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:44,671 INFO:lightkurve.utils:0% (0/41049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24116) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:45,421 INFO:lightkurve.utils:0% (0/24116) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3322) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:46,347 INFO:lightkurve.utils:0% (0/3322) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/37704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:46,511 INFO:lightkurve.utils:0% (0/37704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3508) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:46,710 INFO:lightkurve.utils:0% (0/3508) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/12373) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:46,720 INFO:lightkurve.utils:0% (0/12373) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:47,055 INFO:lightkurve.utils:0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:47,237 INFO:lightkurve.utils:0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30091) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:47,391 INFO:lightkurve.utils:0% (0/30091) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:47,872 INFO:lightkurve.utils:0% (0/14725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/13442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:47,955 INFO:lightkurve.utils:0% (0/13442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,211 INFO:lightkurve.utils:0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9165) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,274 INFO:lightkurve.utils:0% (0/9165) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11608) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,315 INFO:lightkurve.utils:0% (0/11608) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9144) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,327 INFO:lightkurve.utils:0% (0/9144) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/87442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,523 INFO:lightkurve.utils:0% (0/87442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,719 INFO:lightkurve.utils:0% (0/2464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2318) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,891 INFO:lightkurve.utils:0% (0/2318) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:48,991 INFO:lightkurve.utils:0% (0/10458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10827) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,035 INFO:lightkurve.utils:0% (0/10827) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14366) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,066 INFO:lightkurve.utils:0% (0/14366) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,212 INFO:FeatureExtractorNotebook:Completed 1400/2732
0% (0/35039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,384 INFO:lightkurve.utils:0% (0/35039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,459 INFO:lightkurve.utils:0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10639) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,493 INFO:lightkurve.utils:0% (0/10639) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,671 INFO:lightkurve.utils:0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,878 INFO:lightkurve.utils:0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/54620) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:49,922 INFO:lightkurve.utils:0% (0/54620) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/62270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:50,236 INFO:lightkurve.utils:0% (0/62270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/61152) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:50,290 INFO:lightkurve.utils:0% (0/61152) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15721) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:50,310 INFO:lightkurve.utils:0% (0/15721) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11033) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:50,698 INFO:lightkurve.utils:0% (0/11033) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25698) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:50,959 INFO:lightkurve.utils:0% (0/25698) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15833) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,091 INFO:lightkurve.utils:0% (0/15833) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28732) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,093 INFO:lightkurve.utils:0% (0/28732) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,210 INFO:lightkurve.utils:0% (0/14464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,270 INFO:lightkurve.utils:0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,270 INFO:lightkurve.utils:0% (0/35499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/66139) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,338 INFO:lightkurve.utils:0% (0/66139) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43084) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,490 INFO:lightkurve.utils:0% (0/43084) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22228) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:51,907 INFO:lightkurve.utils:0% (0/22228) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24280) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:52,092 INFO:lightkurve.utils:0% (0/24280) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:52,106 INFO:lightkurve.utils:0% (0/30254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/36438) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:52,807 INFO:lightkurve.utils:0% (0/36438) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/20468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:53,004 INFO:lightkurve.utils:0% (0/20468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2926) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:53,065 INFO:lightkurve.utils:0% (0/2926) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/6923) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:53,205 INFO:lightkurve.utils:0% (0/6923) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/67304) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:53,263 INFO:lightkurve.utils:0% (0/67304) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23696) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:53,849 INFO:lightkurve.utils:0% (0/23696) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24507) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:53,890 INFO:lightkurve.utils:0% (0/24507) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/59527) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:54,062 INFO:lightkurve.utils:0% (0/59527) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/40083) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:54,104 INFO:lightkurve.utils:0% (0/40083) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/61191) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:54,119 INFO:lightkurve.utils:0% (0/61191) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/60088) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:54,702 INFO:lightkurve.utils:0% (0/60088) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/76725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:55,357 INFO:lightkurve.utils:0% (0/76725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/4411) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:35:55,855 INFO:lightkurve.utils:0% (0/4411) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Saved 2732 rows and 60 columns to /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_QC.parquet
====================================================================================================
Running feature extraction case: SpocTesscutComparisonDetrend
Input:  /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_Metadata_Consolidated_Detrended.parquet
Output: /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_Detrended.parquet
====================================================================================================

0% (0/14848) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,327 INFO:lightkurve.utils:0% (0/14848) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/12676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,346 INFO:lightkurve.utils:0% (0/12676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31559) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,371 INFO:lightkurve.utils:0% (0/31559) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25561) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,389 INFO:lightkurve.utils:0% (0/25561) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31406) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,391 INFO:lightkurve.utils:0% (0/31406) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/34777) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,418 INFO:lightkurve.utils:0% (0/34777) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/45957) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,428 INFO:lightkurve.utils:0% (0/45957) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/145610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,540 INFO:lightkurve.utils:0% (0/145610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43481) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,555 INFO:lightkurve.utils:0% (0/43481) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/60189) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,564 INFO:lightkurve.utils:0% (0/60189) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/130950) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,571 INFO:lightkurve.utils:0% (0/130950) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/138311) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/97313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/218163) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,579 INFO:lightkurve.utils:0% (0/138311) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/265282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,655 INFO:lightkurve.utils:0% (0/97313) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,690 INFO:lightkurve.utils:0% (0/218163) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,717 INFO:lightkurve.utils:0% (0/265282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/253786) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:01,977 INFO:lightkurve.utils:0% (0/253786) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16341) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:03,250 INFO:lightkurve.utils:0% (0/16341) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16338) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:03,528 INFO:lightkurve.utils:0% (0/16338) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48349) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:04,310 INFO:lightkurve.utils:0% (0/48349) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:04,348 INFO:lightkurve.utils:0% (0/48355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/134863) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:04,360 INFO:lightkurve.utils:0% (0/134863) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/367753) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:04,477 INFO:lightkurve.utils:0% (0/367753) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32818) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:04,889 INFO:lightkurve.utils:0% (0/32818) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/120512) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:04,930 INFO:lightkurve.utils:0% (0/120512) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/108750) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:05,719 INFO:lightkurve.utils:0% (0/108750) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/33867) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:05,725 INFO:lightkurve.utils:0% (0/33867) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43540) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:05,763 INFO:lightkurve.utils:0% (0/43540) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/66976) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:05,940 INFO:lightkurve.utils:0% (0/66976) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/149459) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:06,038 INFO:lightkurve.utils:0% (0/149459) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/103365) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:06,401 INFO:lightkurve.utils:0% (0/103365) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/71259) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:07,088 INFO:lightkurve.utils:0% (0/71259) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/103560) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:07,525 INFO:lightkurve.utils:0% (0/103560) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/68871) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:07,529 INFO:lightkurve.utils:0% (0/68871) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/54202) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:07,774 INFO:lightkurve.utils:0% (0/54202) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/201409) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:08,177 INFO:lightkurve.utils:0% (0/201409) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/29770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:08,395 INFO:lightkurve.utils:0% (0/29770) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48919) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:08,800 INFO:lightkurve.utils:0% (0/48919) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/7230) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:09,002 INFO:lightkurve.utils:0% (0/7230) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47520) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:09,537 INFO:lightkurve.utils:0% (0/47520) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/47456) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:09,776 INFO:lightkurve.utils:0% (0/47456) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9626) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,064 INFO:lightkurve.utils:0% (0/9626) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/50394) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,344 INFO:lightkurve.utils:0% (0/50394) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,550 INFO:lightkurve.utils:0% (0/25355) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/100953) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,614 INFO:lightkurve.utils:0% (0/100953) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/82817) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,696 INFO:lightkurve.utils:0% (0/82817) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/114136) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,762 INFO:lightkurve.utils:0% (0/114136) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/872279) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:10,940 INFO:lightkurve.utils:0% (0/872279) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/912008) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:11,044 INFO:lightkurve.utils:0% (0/912008) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/238480) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:11,403 INFO:lightkurve.utils:0% (0/238480) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:11,610 INFO:lightkurve.utils:0% (0/31942) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:12,194 INFO:lightkurve.utils:0% (0/28317) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/150282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:12,250 INFO:lightkurve.utils:0% (0/150282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30268) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:12,603 INFO:lightkurve.utils:0% (0/30268) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/39027) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:13,047 INFO:lightkurve.utils:0% (0/39027) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9809) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:13,205 INFO:lightkurve.utils:0% (0/9809) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/29862) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:13,222 INFO:lightkurve.utils:0% (0/29862) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:13,390 INFO:lightkurve.utils:0% (0/25370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/77225) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:13,742 INFO:lightkurve.utils:0% (0/77225) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/16452) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:14,095 INFO:lightkurve.utils:0% (0/16452) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/148113) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:14,286 INFO:lightkurve.utils:0% (0/148113) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/45909) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:15,241 INFO:lightkurve.utils:0% (0/45909) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/250370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:15,416 INFO:lightkurve.utils:0% (0/250370) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/235425) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:15,527 INFO:lightkurve.utils:0% (0/235425) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/511114) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:15,772 INFO:lightkurve.utils:0% (0/511114) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/237610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:16,062 INFO:lightkurve.utils:0% (0/237610) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/247385) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:16,350 INFO:lightkurve.utils:0% (0/247385) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/106270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:16,393 INFO:lightkurve.utils:0% (0/106270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/70392) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:16,698 INFO:lightkurve.utils:0% (0/70392) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/124823) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:17,089 INFO:lightkurve.utils:0% (0/124823) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/295794) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:17,386 INFO:lightkurve.utils:0% (0/295794) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:17,483 INFO:lightkurve.utils:0% (0/14676) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14683) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:17,630 INFO:lightkurve.utils:0% (0/14683) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/62748) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:18,095 INFO:lightkurve.utils:0% (0/62748) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:18,916 INFO:lightkurve.utils:0% (0/15331) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/49629) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:19,051 INFO:lightkurve.utils:0% (0/49629) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/57323) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:19,057 INFO:lightkurve.utils:0% (0/57323) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/57435) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:19,073 INFO:lightkurve.utils:0% (0/57435) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/126141) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:19,392 INFO:lightkurve.utils:0% (0/126141) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/151975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:19,722 INFO:lightkurve.utils:0% (0/151975) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/32714) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:20,911 INFO:lightkurve.utils:0% (0/32714) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/7072) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:21,052 INFO:lightkurve.utils:0% (0/7072) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17073) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:21,294 INFO:lightkurve.utils:0% (0/17073) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/88039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:21,297 INFO:lightkurve.utils:0% (0/88039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48403) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:21,612 INFO:lightkurve.utils:0% (0/48403) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/103525) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:41:21,885 INFO:lightkurve.utils:0% (0/103525) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Saved 1012 rows and 60 columns to /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_Detrended.parquet
====================================================================================================
Running feature extraction case: QlpTesscutComparisonDetrend
Input:  /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_Metadata_Consolidated_Detrended.parquet
Output: /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_Detrended.parquet
====================================================================================================

2026-09-07 01:44:16,240 INFO:FeatureExtractorNotebook:Completed 100/2732
2026-09-07 01:44:37,856 INFO:FeatureExtractorNotebook:Completed 200/2732
2026-09-07 01:45:02,077 INFO:FeatureExtractorNotebook:Completed 300/2732
2026-09-07 01:45:26,188 INFO:FeatureExtractorNotebook:Completed 400/2732
2026-09-07 01:45:45,021 INFO:FeatureExtractorNotebook:Completed 500/2732
2026-09-07 01:46:12,119 INFO:FeatureExtractorNotebook:Completed 600/2732
2026-09-07 01:46:41,334 INFO:FeatureExtractorNotebook:Completed 700/2732
2026-09-07 01:47:07,820 INFO:FeatureExtractorNotebook:Completed 800/2732
2026-09-07 01:47:26,975 INFO:FeatureExtractorNotebook:Completed 900/2732
2026-09-07 01:47:44,619 INFO:FeatureExtractorNotebook:Completed 1000/2732
2026-09-07 01:48:07,166 INFO:FeatureExtractorNotebook:Completed 1100/2732
2026-09-07 01:48:25,468 INFO:FeatureExtractorNotebook:Completed 1200/2732
2026-09-07 01:48:46,054 INFO:FeatureExtractorNotebook:Completed 1300/2732
0% (0/33018) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:54,018 INFO:lightkurve.utils:0% (0/33018) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:54,470 INFO:lightkurve.utils:0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:54,925 INFO:lightkurve.utils:0% (0/22450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:55,280 INFO:lightkurve.utils:0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:55,351 INFO:lightkurve.utils:0% (0/28868) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/42627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:55,688 INFO:lightkurve.utils:0% (0/42627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/48327) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:56,565 INFO:lightkurve.utils:0% (0/48327) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:57,517 INFO:lightkurve.utils:0% (0/31244) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28434) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,199 INFO:lightkurve.utils:0% (0/28434) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28826) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,316 INFO:lightkurve.utils:0% (0/28826) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/33175) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,488 INFO:lightkurve.utils:0% (0/33175) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,577 INFO:lightkurve.utils:0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28834) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,581 INFO:lightkurve.utils:0% (0/28834) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,771 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,791 INFO:lightkurve.utils:0% (0/28638) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,858 INFO:lightkurve.utils:0% (0/30879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24791) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,860 INFO:lightkurve.utils:0% (0/25049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:58,888 INFO:lightkurve.utils:0% (0/24791) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14646) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:59,202 INFO:lightkurve.utils:0% (0/14646) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/31397) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:59,264 INFO:lightkurve.utils:0% (0/31397) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19194) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:59,387 INFO:lightkurve.utils:0% (0/19194) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/12142) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:59,864 INFO:lightkurve.utils:0% (0/12142) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11161) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:59,900 INFO:lightkurve.utils:0% (0/11161) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:48:59,995 INFO:lightkurve.utils:0% (0/15627) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/19881) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:00,312 INFO:lightkurve.utils:0% (0/19881) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30606) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:01,532 INFO:lightkurve.utils:0% (0/30606) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/41049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:02,215 INFO:lightkurve.utils:0% (0/41049) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24116) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:02,549 INFO:lightkurve.utils:0% (0/24116) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/37704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:02,948 INFO:lightkurve.utils:0% (0/37704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3322) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:03,166 INFO:lightkurve.utils:0% (0/3322) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3508) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:03,369 INFO:lightkurve.utils:0% (0/3508) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/12373) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:03,708 INFO:lightkurve.utils:0% (0/12373) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:03,790 INFO:lightkurve.utils:0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:04,256 INFO:lightkurve.utils:0% (0/17499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30091) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:04,461 INFO:lightkurve.utils:0% (0/30091) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:04,704 INFO:lightkurve.utils:0% (0/14725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/13442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:04,874 INFO:lightkurve.utils:0% (0/13442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,076 INFO:lightkurve.utils:0% (0/3011) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9144) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,223 INFO:lightkurve.utils:0% (0/9144) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/9165) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,264 INFO:lightkurve.utils:0% (0/9165) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,463 INFO:lightkurve.utils:0% (0/2464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11608) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,483 INFO:lightkurve.utils:0% (0/11608) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2318) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,515 INFO:lightkurve.utils:0% (0/2318) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/87442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,588 INFO:lightkurve.utils:0% (0/87442) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10827) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:05,903 INFO:lightkurve.utils:0% (0/10827) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,018 INFO:lightkurve.utils:0% (0/10458) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,202 INFO:FeatureExtractorNotebook:Completed 1400/2732
0% (0/14366) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,343 INFO:lightkurve.utils:0% (0/14366) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,367 INFO:lightkurve.utils:0% (0/35039) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/10639) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,443 INFO:lightkurve.utils:0% (0/10639) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,475 INFO:lightkurve.utils:0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,494 INFO:lightkurve.utils:0% (0/11081) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,524 INFO:lightkurve.utils:0% (0/43439) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/54620) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,532 INFO:lightkurve.utils:0% (0/54620) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15721) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,810 INFO:lightkurve.utils:0% (0/15721) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/11033) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,835 INFO:lightkurve.utils:0% (0/11033) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/61152) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,971 INFO:lightkurve.utils:0% (0/61152) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/62270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:06,988 INFO:lightkurve.utils:0% (0/62270) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/15833) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:07,591 INFO:lightkurve.utils:0% (0/15833) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/25698) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:07,681 INFO:lightkurve.utils:0% (0/25698) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/28732) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:07,764 INFO:lightkurve.utils:0% (0/28732) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:07,983 INFO:lightkurve.utils:0% (0/14464) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:08,109 INFO:lightkurve.utils:0% (0/14624) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/66139) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:08,546 INFO:lightkurve.utils:0% (0/66139) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/35499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:08,581 INFO:lightkurve.utils:0% (0/35499) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/22228) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:08,806 INFO:lightkurve.utils:0% (0/22228) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/43084) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:08,840 INFO:lightkurve.utils:0% (0/43084) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/30254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:09,353 INFO:lightkurve.utils:0% (0/30254) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/36438) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:09,769 INFO:lightkurve.utils:0% (0/36438) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24280) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:09,788 INFO:lightkurve.utils:0% (0/24280) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/20468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,169 INFO:lightkurve.utils:0% (0/20468) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/67304) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,219 INFO:lightkurve.utils:0% (0/67304) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/2926) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,302 INFO:lightkurve.utils:0% (0/2926) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/6923) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,442 INFO:lightkurve.utils:0% (0/6923) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/23696) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,787 INFO:lightkurve.utils:0% (0/23696) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/24507) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,802 INFO:lightkurve.utils:0% (0/24507) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/59527) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:10,962 INFO:lightkurve.utils:0% (0/59527) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/40083) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:11,202 INFO:lightkurve.utils:0% (0/40083) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/61191) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:11,213 INFO:lightkurve.utils:0% (0/61191) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/60088) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:11,359 INFO:lightkurve.utils:0% (0/60088) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/76725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:12,087 INFO:lightkurve.utils:0% (0/76725) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
0% (0/4411) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-09-07 01:49:12,494 INFO:lightkurve.utils:0% (0/4411) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Saved 2732 rows and 60 columns to /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_Detrended.parquet

# Quick Sanity Checks

In [13]:
display(FeatureDf.head())

NumericColumns = FeatureDf.select_dtypes(include=[np.number]).columns
MissingRate = FeatureDf[NumericColumns].isna().mean().sort_values(ascending=False)
display(MissingRate.head(30))

,FeatureStatus,FeatureError,family,VSXType,VSXId,lightCurvePath,rawLightCurvePath,QualityLabel,QualityScore,Provenance,...,LsPowerRatio21,LsPowerRatio31,LsPeriodRatio21,LsPeriodRatio31,PhaseCurveStd,PhaseCurveRange,PhaseCurveSmoothness,PhasePeakPhase,PhaseTroughPhase,PhasePeakToTroughPhaseDelta
0,ok,NaN,LONG_PERIOD,M,000-BBB-200,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,clean,0.0,QLP,...,0.991310,0.986906,0.889744,1.000721,0.470003,1.674737,0.255603,0.575001,0.274186,0.300815
1,ok,NaN,LONG_PERIOD,M,000-BBB-325,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,clean,0.0,QLP,...,0.991209,0.989057,0.956909,0.956085,1.034441,3.297068,0.563557,0.635151,0.510961,0.124190
2,ok,NaN,LONG_PERIOD,M,000-BBB-522,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,clean,0.0,QLP,...,0.996309,0.994892,0.999091,0.955674,0.736237,2.312235,0.257815,0.924987,0.473784,0.451203
3,ok,NaN,LONG_PERIOD,SRB,000-BBC-842,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,clean,0.0,QLP,...,0.992203,0.985585,0.935862,0.937064,0.279500,1.197970,0.214829,0.527088,0.018863,0.491776
4,ok,NaN,LONG_PERIOD,M,000-BBC-885,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,clean,0.0,QLP,...,0.979301,0.943658,0.999168,1.000834,0.426910,1.353863,0.174807,0.675462,0.274613,0.400849

MedianCadenceDays             0.004758
FluxIqr                       0.004758
FluxStd                       0.004758
TimeSpanDays                  0.004758
FluxP90                       0.004758
FluxP10                       0.004758
FluxP05                       0.004758
FluxMad                       0.004758
FluxMedian                    0.004758
FluxAmplitude                 0.004758
FluxP95                       0.004758
TailLower                     0.004758
TailUpper                     0.004758
FluxKurtosis                  0.004758
FluxSkewness                  0.004758
FluxPercentAmplitude90To10    0.004758
FluxPercentAmplitude95To5     0.004758
LsPeriod2                     0.004758
LsPeriod3                     0.004758
LsPower2                      0.004758
LsPower3                      0.004758
LsPeakPowerGap12              0.004758
LsPeakPowerGap23              0.004758
TailAsymmetry                 0.004758
TailRatio                     0.004758
EtaVonNeumann                 0.004758
MaxAbsSlope                   0.004758
MedianAbsSuccessiveDiff       0.004758
FractionBeyond1Std            0.004758
FractionBeyond2Std            0.004758
dtype: float64

In [14]:
if "family" in FeatureDf.columns:
    display(pd.crosstab(FeatureDf["family"], FeatureDf["FeatureStatus"], dropna=False))

FeatureStatus    failed   ok  too_few_cadences
family
CEPHEID               0  472                 1
CV                    0    4                 0
DSCT_SXPHE            0  422                 0
ECLIPSING             0  220                 0
ELLIPSOIDAL_ROT       0  302                 0
LONG_PERIOD           0  978                 0
RRLYR                 0   35                 0
XRAY                  0   20                 0
YSO                   0  266                 1
NaN                  11    0                 0

## Consolidated Output Summary

The summary reports the configured input path, output path, dimensions, and feature-extraction status counts for each completed extraction case.

In [15]:
SummaryRows = []

for CaseName, Paths in FeatureExtractionCases.items():
    CaseFeatureDf = FeatureDfByCase.get(CaseName)

    if CaseFeatureDf is None:
        print(f"{CaseName}: run the feature-extraction cell first.")
        continue

    SummaryRows.append({
        "Case": CaseName,
        "InputMetadataPath": str(Paths["InputMetadataPath"]),
        "OutputFeaturePath": str(Paths["OutputFeaturePath"]),
        "Rows": len(CaseFeatureDf),
        "Columns": len(CaseFeatureDf.columns),
    })

    print("=" * 100)
    print(CaseName)
    print("=" * 100)
    print("InputMetadataPath:", Paths["InputMetadataPath"])
    print("OutputFeaturePath:", Paths["OutputFeaturePath"])
    print("Shape:", CaseFeatureDf.shape)

    if "FeatureStatus" in CaseFeatureDf.columns:
        display(
            CaseFeatureDf["FeatureStatus"]
            .value_counts(dropna=False)
            .rename_axis("FeatureStatus")
            .reset_index(name="Count")
        )

if SummaryRows:
    display(pd.DataFrame(SummaryRows))

====================================================================================================
NoDetrend
====================================================================================================
InputMetadataPath: /data/projects/TESS-research/data_pipeline/TESSCache/TESSAugmented_QC.parquet
OutputFeaturePath: /data/projects/TESS-research/feature_extraction/TESS_features.parquet
Shape: (7294, 60)

      FeatureStatus  Count
0                ok   7281
1            failed     11
2  too_few_cadences      2

====================================================================================================
TesscutConditionalDetrend
====================================================================================================
InputMetadataPath: /data/projects/TESS-research/detrend_tesscut/output/TESSAugmented_QC_tesscut_conditional_detrended.parquet
OutputFeaturePath: /data/projects/TESS-research/feature_extraction/TESS_conditional_detrended_features.parquet
Shape: (7294, 60)

      FeatureStatus  Count
0                ok   7281
1            failed     11
2  too_few_cadences      2

====================================================================================================
SpocTesscutComparisonQC
====================================================================================================
InputMetadataPath: /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_Metadata_Consolidated_QC.parquet
OutputFeaturePath: /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_QC.parquet
Shape: (1012, 60)

  FeatureStatus  Count
0            ok   1012

====================================================================================================
QlpTesscutComparisonQC
====================================================================================================
InputMetadataPath: /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_Metadata_Consolidated_QC.parquet
OutputFeaturePath: /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_QC.parquet
Shape: (2732, 60)

      FeatureStatus  Count
0                ok   2719
1            failed     11
2  too_few_cadences      2

====================================================================================================
SpocTesscutComparisonDetrend
====================================================================================================
InputMetadataPath: /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_Metadata_Consolidated_Detrended.parquet
OutputFeaturePath: /data/projects/TESS-research/data_pipeline/SPOC_TESSCutCache/SPOC_TESSCut_features_Detrended.parquet
Shape: (1012, 60)

  FeatureStatus  Count
0            ok   1012

====================================================================================================
QlpTesscutComparisonDetrend
====================================================================================================
InputMetadataPath: /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_Metadata_Consolidated_Detrended.parquet
OutputFeaturePath: /data/projects/TESS-research/data_pipeline/QLP_TESSCutCache/QLP_TESSCut_features_Detrended.parquet
Shape: (2732, 60)

      FeatureStatus  Count
0                ok   2719
1            failed     11
2  too_few_cadences      2

,Case,InputMetadataPath,OutputFeaturePath,Rows,Columns
0,NoDetrend,/data/projects/TESS-research/data_pipeline/TES...,/data/projects/TESS-research/feature_extractio...,7294,60
1,TesscutConditionalDetrend,/data/projects/TESS-research/detrend_tesscut/o...,/data/projects/TESS-research/feature_extractio...,7294,60
2,SpocTesscutComparisonQC,/data/projects/TESS-research/data_pipeline/SPO...,/data/projects/TESS-research/data_pipeline/SPO...,1012,60
3,QlpTesscutComparisonQC,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,2732,60
4,SpocTesscutComparisonDetrend,/data/projects/TESS-research/data_pipeline/SPO...,/data/projects/TESS-research/data_pipeline/SPO...,1012,60
5,QlpTesscutComparisonDetrend,/data/projects/TESS-research/data_pipeline/QLP...,/data/projects/TESS-research/data_pipeline/QLP...,2732,60